---
title: "SNA-Projekt_Trumps-Truth-Social-Nutzung_nh113-ms657-mf199-sm281-rk109"
author: "Nina Hafner, Malin Schröder, Marie Friedrich, Stella Marrone, Rebecca Kunz"
date: "Wintersemester 25/26"
output: html_document
---

# Setup und Lernziele

**Quellen:** [GitHub](https://github.com/ninah113/SNA-Projekt_Trump-Truth-Social/tree/main) [Codebuch](https://github.com/ninah113/SNA-Projekt_Trump-Truth-Social/blob/main/Codebuch.md)

## Laden der Programmbibliotheken

```{r}

library(igraph)
library(tidygraph)
library(ggraph)
```

# Netzwerk einlesen

```{r setup und Netzwerk einlesen}

el <- read.csv(
  "https://raw.githubusercontent.com/ninah113/SNA-Projekt_Trump-Truth-Social/refs/heads/main/Merge_final_Edgelist.csv",
  header = TRUE, sep = ",", stringsAsFactors = FALSE
)

nl <- read.csv(
  "https://raw.githubusercontent.com/ninah113/SNA-Projekt_Trump-Truth-Social/refs/heads/main/Merge_final_Nodelist.csv",
  header = TRUE, sep = ",", stringsAsFactors = FALSE
)

t <- graph_from_data_frame(
  d = el,
  vertices = nl,
  directed = TRUE
)

#name_first <- 

```

# Visualisierung

```{r Visualisierung SNA Projekt, fig.height=9, fig.width=12}

# Visualisierung
V(t)$color <- "blue"

plot(t,
     asp=0,
     layout=layout_with_fr,
     #vertex.size=degree(t)/0.6,
     vertex.size=2,
     edge.arrow.size=.1,
     main = "Trump Truth Social Netzwerk"
     )

```




```{r}
set.seed(123) # Netzwerk sieht bei bestimmten Layouts mit jedem Run anders aus; set.seed() verhindert das. 
ggraph(t, layout = "fr")+ # Layouts beeinflussen z.B., wie sich Knoten und Kanten ggü. einander verhalten
geom_edge_link(color = "blue", width = 1)+ # Kantenfarbe und -dicke  
geom_node_point(color = "red", size = 0.5)+ # Knotenfarbe und -größe  
geom_node_text(aes(label = name), repel = TRUE)+ # Name wird als Label angezeigt  
labs(title = "Trump Truth Social Netzwerk", # Überschrift       
subtitle = "") # Subtitle


```
